// Local username actions
export const SET_USER_ID = 'SET_USER_ID';

// Notification related constants
export const NOTIFICATION_EXPIRED = 'NOTIFICATION_EXPIRED';

// Websockets actions sent
export const TEST_WEBSOCKET = 'TEST_WEBSOCKET';
export const REGISTER = 'REGISTER';
export const CHANGE_DISPLAY_IMAGE = 'CHANGE_DISPLAY_IMAGE';
export const CHANGE_ACTIVITY = 'CHANGE_ACTIVITY';

// Websockets actions received
export const USER_TESTED = 'USER_TESTED';
export const REGISTERED = 'REGISTERED';
export const USER_JOINED = 'USER_JOINED';
export const USER_LEFT = 'USER_LEFT';
export const DISPLAY_IMAGE_CHANGED = 'DISPLAY_IMAGE_CHANGED';
export const ACTIVITY_CHANGED = 'ACTIVITY_CHANGED';

// Basic room setup actions
export const SET_ROOM_ID = 'SET_ROOM_ID';
export const SET_MEETING_TYPE = 'SET_MEETING_TYPE';
export const SET_ROOM_DIMENSIONS = 'SET_ROOM_DIMENSIONS';

// Video actions
export const DEVICE_READY = 'DEVICE_READY';
export const AUDIO_MUTED = 'AUDIO_MUTED';
export const AUDIO_UNMUTED = 'AUDIO_UNMUTED';
export const VIDEO_MUTED = 'VIDEO_MUTED';
export const VIDEO_UNMUTED = 'VIDEO_UNMUTED';
export const DEVICE_CONNECTED = 'DEVICE_CONNECTED';
export const DEVICE_DISCONNECTED = 'DEVICE_DISCONNECTED';
export const ENTERED_ROOM = 'ENTERED_ROOM';
export const LEFT_ROOM = 'LEFT_ROOM';

// Local participant video actions
export const LOCAL_PARTICIPANT_JOINING_ROOM = 'LOCAL_PARTICIPANT_JOINING_ROOM';
export const LOCAL_PARTICIPANT_JOINED_ROOM = 'LOCAL_PARTICIPANT_JOINED_ROOM';
export const LOCAL_PARTICIPANT_LEAVING_ROOM = 'LOCAL_PARTICIPANT_LEAVING_ROOM';
export const LOCAL_PARTICIPANT_LEFT_ROOM = 'LOCAL_PARTICIPANT_LEFT_ROOM';

// Remote participant video actions
export const PARTICIPANTS_UPDATED = 'PARTICIPANTS_UPDATED';
export const PARTICIPANT_JOINED_VIDEO = 'PARTICIPANT_JOINED_VIDEO';
export const PARTICIPANT_LEFT_VIDEO = 'PARTICIPANT_LEFT_VIDEO';
export const PARTICIPANT_JOINING_ROOM = 'PARTICIPANT_JOINING_ROOM';
export const PARTICIPANT_JOINED_ROOM = 'PARTICIPANT_JOINED_ROOM';
export const PARTICIPANT_LEAVING_ROOM = 'PARTICIPANT_LEAVING_ROOM';
export const PARTICIPANT_LEFT_ROOM = 'PARTICIPANT_LEFT_ROOM';

// Available room types
export const SMALL_GROUP_VIDEO = 'SMALL_GROUP_VIDEO';
export const MEDIUM_GROUP_VIDEO = 'MEDIUM_GROUP_VIDEO';
export const SMALL_GROUP_ACTIVITY = 'SMALL_GROUP_ACTIVITY';
export const MEDIUM_GROUP_ACTIVITY = 'MEDIUM_GROUP_ACTIVITY';

// Screensharing
export const START_SCREENSHARE = 'START_SCREENSHARE';
export const STARTED_SCREENSHARE = 'STARTED_SCREENSHARE';
export const END_SCREENSHARE = 'END_SCREENSHARE';
export const ENDED_SCREENSHARE = 'ENDED_SCREENSHARE';

// Activity types
export const SCREENSHARE = 'SCREENSHARE';